service: todo-webapp

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  region: eu-south-1

functions:
  register:
    handler: functions/register.handler
    events:
      - http:
          path: api/register
          method: post
          cors: true
  login:
    handler: functions/login.handler
    events:
      - http:
          path: api/login
          method: post
          cors: true
  createCollection:
    handler: functions/createCollection.handler
    events:
      - http:
          path: api/collections
          method: post
          cors: true
  getCollections:
    handler: functions/getCollections.handler
    events:
      - http:
          path: api/collections
          method: get
          cors: true
  changeCollection:
    handler: functions/changeCollection.handler
    events:
      - http:
          path: api/collections/{id}
          method: patch
          cors: true
  deleteCollection:
    handler: functions/deleteCollection.handler
    events:
      - http:
          path: api/collections/{id}
          method: delete
          cors: true
  createTodo:
    handler: functions/createTodo.handler
    events:
      - http:
          path: api/todos
          method: post
          cors: true
  getTodos:
    handler: functions/getTodos.handler
    events:
      - http:
          path: api/todos/{id}
          method: get
          cors: true
  setCompleted:
    handler: functions/setCompleted.handler
    events:
      - http:
          path: api/todos/{id}
          method: patch
          cors: true
  deleteTodo:
    handler: functions/deleteTodo.handler
    events:
      - http:
          path: api/todos/{id}
          method: delete
          cors: true

plugins:
  - serverless-offline
